### PR TITLE
[Triton] Reconstruction -- unify greedy search and fast beam search for offline model

### PR DESCRIPTION
**Pull request by wd929**

### CODE REVIEW

**Comment by csukuangfj** [comment]
Thanks! Is it ready for merge?

**Comment by wd929** [comment]
Yes. It's ready for merge. Have already test the codes ^^
Thanks!!

**Comment by wd929** [comment]
@csukuangfj Fangjun, would you mind review and merge this PR? Thanks!

**Comment by csukuangfj** [comment]
Thanks!

**Pull request merged**
