### PR TITLE
[Ready] Add Triton Stateful Model for Streaming ASR 

### PR DESCRIPTION
**Pull request by yuekaizhang**
This PR adds streaming ASR service through triton stateful model. It uses triton sequence batching to automatically batch the requests with [implicate state management ](https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#implicit-state-management) to handle the internal states (attn_cache, cnn_cache etc. )

TODO:
- [x] Update Readme
- [x] Onnx conversion code (May PR it in icefall https://github.com/k2-fsa/icefall/pull/546)
- [x] Unify Streaming and Offline Client
- [ ] Auto-filling config scripts and code cleaning

Below screenshot shows us tritonserver start (right) and inference from client (left).

ezgif-1-794816bd0a

### CODE REVIEW

**Comment by yuekaizhang** [comment]
@csukuangfj  Sorry for the late update, would you mind checking this PR? It uses onnx as backends. In the future PRs, I would like add onnx fp16 inference and fast_beam_search methods.

**Comment by csukuangfj** [comment]
> @csukuangfj Sorry for the late update, would you mind checking this PR? It uses onnx as backends. In the future PRs, I would like add onnx fp16 inference and fast_beam_search methods.

Thanks!

I am reading the code.

**Review by csukuangfj — COMMENTED** [review]
Thanks. Left some comments for typos. Otherwise, it looks good to me.

**Comment by yuekaizhang** [comment]
> Thanks. Left some comments for typos. Otherwise, it looks good to me.

Thx, done.

**Pull request merged**
