### PR TITLE
Rename models to follow icefall convention

### PR DESCRIPTION
**Pull request by ezerhouni**

### CODE REVIEW

**Comment by csukuangfj** [comment]
Could you use
```bash
git grep conformer_rnnt
```
to find all occurrences of `conformer_rnnt` in the repo and replace it with `pruned_transducer_statelessX`?

The same goes for `streaming_conformer_rnnt` -> `streaming_pruned_transducer_statelessX`.

(The `README.md` https://github.com/ezerhouni/sherpa/blob/follow-icefall-naming-convention/README.md has not been updated yet.)

**Comment by ezerhouni** [comment]
@csukuangfj I fixed the remaining "old" name. However, this PR has now a conflict with master. I usually do ```git rebase``` for that but it involves a ```git push -f```, I saw that you try to avoid them, would that be ok or your prefer another method ?

**Comment by csukuangfj** [comment]
> `sherpa/bin/streaming_conformer_rnnt/streaming_server.py`

I suggest using
```bash
git remote add dan https://github.com/k2-fsa/sherpa
git fetch dan
git merge dan/master
# resolve conflicts
git merge --continue
git push
```

**Comment by csukuangfj** [comment]
Or you can use a method that you are most familiar with.
It's better to avoid a force push.

**Comment by csukuangfj** [comment]
Thanks! Will merge after all tests get passed.

**Review by csukuangfj — APPROVED** [review]

**Comment by ezerhouni** [comment]
> Thanks! Will merge after all tests get passed.

Thanks ! I just push another commit for couple of streaming_conformer I missed

**Comment by ezerhouni** [comment]
@csukuangfj If it is ok for you, could we merge it ?

**Comment by csukuangfj** [comment]
> @csukuangfj If it is ok for you, could we merge it ?

Thanks. You can merge it when you think it is OK.

**Pull request merged**
