### PR TITLE
Streaming asr time stamp

### PR DESCRIPTION
**Pull request by ezerhouni**
Copy from : https://github.com/k2-fsa/sherpa/pull/119

### CODE REVIEW

**Comment by ezerhouni** [comment]
@csukuangfj I have this issue when installing :
```
/sherpa/sherpa/csrc/online_asr.cc:247:29: error: invalid initialization of reference of type ‘const std::vector<int, std::allocator<int> >&’ from expression of type ‘std::vector<std::vector<int, std::allocator<int> > >*’
  247 |                             &all_hyps, &all_num_trailing_blank_frames)

```
Did you have the fix somewhere or should I take care of it ? (I saw that you made the code)

**Comment by csukuangfj** [comment]
I see.

The master code:

https://github.com/k2-fsa/sherpa/blob/b1634288e34f97bc5985eca87126d07f3294bda8/sherpa/csrc/online_asr.cc#L246-L247

Code of this PR

https://github.com/k2-fsa/sherpa/blob/8990519d677de4469c9064b4fffdc463a92e21c8/sherpa/csrc/rnnt_beam_search.cc#L205-L211

---

This PR changes the signature of `StreamingGreedySearch`, so we need to change the places where `StreamingGreedySearch` is invoked in C++.

**Comment by csukuangfj** [comment]
online_asr.cc was added after #119 is created. Please change online_asr.cc accordingly. For now, just pass an empty vector to `StreamingGreedySearch` from online_asr.cc should be fine.

**Comment by ezerhouni** [comment]
@csukuangfj FYI, there is also ```frame_offset``` to set

**Comment by ezerhouni** [comment]
@csukuangfj Can you have a look ? I think the cpp is broken though, I will try to have a look today

**Review by csukuangfj — APPROVED** [review]
Looks great to me. Thanks for the help.

**Comment by csukuangfj** [comment]
> @csukuangfj Can you have a look ? I think the cpp is broken though, I will try to have a look today

It is just a dummy implementation for the OnlineAsr, but I compiles, I think. What do you mean `cpp is broken`?

**Comment by ezerhouni** [comment]
@csukuangfj For the ```frame_offset``` in cpp, I just pass empty vector so not sure it produce to correct output (but it compiles)

**Comment by csukuangfj** [comment]
> @csukuangfj For the ```frame_offset``` in cpp, I just pass empty vector so not sure it produce to correct output (but it compiles)

The timestamp won't be correct, but it won't affect the recognition results. Since we are not returning the timestamp information in c++, the current dummy implementation should be fine. We can fix it in a separate PR to also return timestamp in c++.

**Comment by csukuangfj** [comment]
@ezerhouni 
Thanks! I am merging it. We can fix the dummy implementation for c++ api in a separate PR.

**Pull request merged**
