### PR TITLE
Increase tail padding

### PR DESCRIPTION
**Pull request by shaynemei**
Original tail padding is not long enough which causes worse performance compared to icefall decoding:

for example in the tedlium_dev evaluation:
```
...THE ANNUAL ICE IN WINTER AND IT CONTRACTS IN (SUMMER->SU)
...TO TWENTY FEET OF SEA LEVEL AS IS (GREENLAND->GREENLA)
...TO CARBON BASED FUELS LIKE DIRTY COAL (AND->ON) FOREIGN (OIL->O)
...TO WORK MAKE US MORE SECURE AND HELP STOP (GLOBAL WARMING->LOBAL WAR)
...IS BOTH THAT FREEDOM IS IN AND OF ITSELF (GOOD->*)
```

Increasing the padding from 0.3 to 1.0 seems to bring the WER back to the same as icefall:

snap 2023-08-31 at 12 52 24 PM

### CODE REVIEW

**Comment by csukuangfj** [comment]
Could you make it a command line argument?

**Comment by shaynemei** [comment]
> Could you make it a command line argument?

Done, set default to 1.0

**Comment by csukuangfj** [comment]
Thanks!

**Comment by danpovey** [comment]
I am surprised 0.3 secs is not enough, is there anything about Sherpa that
explains this?

**Comment by csukuangfj** [comment]
@shaynemei 

Which streaming model are you using and have you tried other values between [0.3, 1.0]?

**Comment by shaynemei** [comment]
this is the model I used to run the evaluation:
 https://huggingface.co/Zengwei/icefall-asr-librispeech-streaming-zipformer-2023-05-17
 
I've also tried 0.5 on some of the utterances (didn't run full evaluation for WER), and got a little bit more BPE units at the end but still missing one or two BPE units.

**Pull request merged**
