### PR TITLE
Add fast_beam_search_nbest_LG to streaming models

### PR DESCRIPTION
**Pull request by ezerhouni**

### CODE REVIEW

**Comment by ezerhouni** [comment]
@csukuangfj Before merging it, could you update the huggingface repo with :
- tokens.txt
- words.txt
- L.pt
- LG.pt
- Linv.pt

Otherwise ```fast_beam_search_nbest_LG``` won't work (I tested with a local version)

**Comment by csukuangfj** [comment]
> @csukuangfj Before merging it, could you update the huggingface repo with :
> 
> * tokens.txt
> * words.txt
> * L.pt
> * LG.pt
> * Linv.pt
> 
> Otherwise `fast_beam_search_nbest_LG` won't work (I tested with a local version)

Which huggingface repo are your referring to?

**Comment by ezerhouni** [comment]
> > @csukuangfj Before merging it, could you update the huggingface repo with :
> > 
> > * tokens.txt
> > * words.txt
> > * L.pt
> > * LG.pt
> > * Linv.pt
> > 
> > Otherwise `fast_beam_search_nbest_LG` won't work (I tested with a local version)
> 
> Which huggingface repo are your referring to?

The one used in CI job : 

- https://huggingface.co/pkufool/icefall-asr-librispeech-pruned-stateless-streaming-conformer-rnnt4-2022-06-10
- https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13
- https://huggingface.co/Zengwei/icefall-asr-librispeech-conv-emformer-transducer-stateless2-2022-07-05
- https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-stateless-emformer-rnnt2-2022-06-01
- https://huggingface.co/csukuangfj/icefall-aishell-pruned-transducer-stateless3-2022-06-20 --> This one has only the LG missing
- https://huggingface.co/luomingshuang/icefall_asr_wenetspeech_pruned_transducer_stateless5_streaming --> I think this one has all the files

If it is too much of a hassle, we can do a CI with only ```https://huggingface.co/luomingshuang/icefall_asr_wenetspeech_pruned_transducer_stateless5_streaming``` since it has already all the files

**Comment by csukuangfj** [comment]
We will upload all required files to the above huggingface repositories tomorrow.

**Comment by ezerhouni** [comment]
> We will upload all required files to the above huggingface repositories tomorrow.

Thanks @csukuangfj

**Comment by ezerhouni** [comment]
@csukuangfj I will update later today the CI for the lang-dir. I will be out until mid august starting tomorrow.

**Comment by csukuangfj** [comment]
> @csukuangfj I will update later today the CI for the lang-dir. I will be out until mid august starting tomorrow.

Thanks. I think all the above-mentioned repositories now contain the files that are required.

**Review by csukuangfj — APPROVED** [review]

**Comment by ezerhouni** [comment]
Ok let me push some code (later today) and then we can merge

**Comment by ezerhouni** [comment]
Ok, everything seems to work. Merging

**Comment by csukuangfj** [comment]
Thanks!

**Pull request merged**
